-- Sales Performance Analysis
-- Which product have the highest number of units sold?
SELECT `Product type`, SKU, SUM(`Number of products sold`) AS Total_Units_Sold
FROM supply_chain_data
GROUP BY `Product type` , SKU
ORDER BY `Total_Units_Sold` DESC
LIMIT 1;

-- What is the total revenue generated by each product type?
SELECT `Product type`, round(SUM(Price * `Number of products sold`),2) AS Total_Revenue
FROM supply_chain_data
GROUP BY `Product type`;

-- What is the overall revenue generated from all products?
SELECT ROUND(SUM(Price * `Number of products sold`), 2) AS Overall_Revenue
FROM supply_chain_data;

-- Inventory Management Analysis:
-- What is the current availability of each product?

SELECT `Product type`, SKU, (`Stock levels` - SUM(`Number of products sold`)) AS Current_Availability
FROM supply_chain_data
GROUP BY `Product type`, SKU, `Stock levels`;

-- Which products have low stock levels and may need replenishment?
SELECT `Product type`, SKU, `Stock levels`
FROM supply_chain_data
WHERE `Stock levels` < 10;

-- Supplier Performance Analysis
-- Who are the top-performing suppliers based on the number of products sold?

SELECT `Supplier name`, SUM(`Number of products sold`) AS Total_Products_Sold
FROM supply_chain_data
GROUP BY `Supplier name`
ORDER BY Total_Products_Sold DESC;

-- What are the lead times for each supplier to deliver products?

SELECT `Supplier name`, AVG(`Lead time`) AS Average_Lead_Time
FROM supply_chain_data
GROUP BY `Supplier name`;

-- What is the total revenue generated from products supplied by each supplier?

SELECT `Supplier name`, SUM( Price * `Number of products sold`) AS Total_Revenue
FROM supply_chain_data 
GROUP BY `Supplier name`;


-- Shipping Analysis:
-- What are the average shipping times for different shipping carriers?

SELECT `Shipping carriers`, AVG(`Shipping times`) AS Average_Shipping_Time
FROM supply_chain_data
GROUP BY `Shipping carriers`;

-- How do shipping costs vary based on the transportation modes and routes?
SELECT `Transportation modes`, Routes, AVG(`Shipping costs`) AS Average_Shipping_Cost
FROM supply_chain_data
GROUP BY `Transportation modes`, Routes;

-- What is the total shipping cost incurred for each product type?

SELECT `Product type`, SUM(`Shipping costs`) AS Total_Shipping_Cost
FROM supply_chain_data
GROUP BY `Product type`;


-- Cost Analysis:
-- What is the total manufacturing cost for each product type?

SELECT `Product type`, SKU, sum(`Manufacturing costs`) as Total_Manufacturing_cost
FROM supply_chain_data;

-- How do transportation costs contribute to the overall cost of goods sold?

SELECT 
    `Product type`, 
    SUM(`Shipping costs`) AS Total_Transportation_Costs,
    SUM(`Price` * `Number of products sold`) AS Total_Revenue,
    SUM(`Price` * `Number of products sold`) + SUM(`Shipping costs`) AS Total_Cost_of_Goods_Sold,
    (SUM(`Shipping costs`) / (SUM(`Price` * `Number of products sold`) + SUM(`Shipping costs`))) * 100 AS Transportation_Cost_Percentage
FROM supply_chain_data
GROUP BY `Product type`;

-- What is the total cost incurred for each product type including manufacturing, and transportation?

SELECT 
    `Product type`, 
    SUM(`Manufacturing costs`) AS Total_Manufacturing_Costs,
    SUM(`Shipping costs`) AS Total_Transportation_Costs,
    SUM(`Manufacturing costs`) + SUM(`Shipping costs`) AS Total_Cost_Incurred
FROM supply_chain_data
GROUP BY `Product type`;

-- What are the purchasing patterns of different customer demographics?

SELECT 
    `Customer demographics`,
    COUNT(*) AS Total_Orders,
    SUM(`Number of products sold`) AS Total_Products_Sold,
    SUM(`Price` * `Number of products sold`) AS Total_Revenue,
    AVG(`Number of products sold`) AS Average_Order_Size
FROM supply_chain_data
GROUP BY `Customer demographics`;

-- Which customer demographics contribute the most to the revenue?

SELECT 
    `Customer demographics`,
    SUM(`Price` * `Number of products sold`) AS Total_Revenue
FROM supply_chain_data
GROUP BY  `Customer demographics`
ORDER BY Total_Revenue DESC;

-- What products are popular among different customer demographics?

SELECT 
`Customer demographics`,
    `Product type`,
    SUM(`Number of products sold`) AS Total_Products_Sold
FROM supply_chain_data
GROUP BY `Customer demographics`, `Product type`
ORDER BY `Customer demographics`, Total_Products_Sold DESC;

-- Supplier and Transportation Optimization:
-- Which suppliers offer the most cost-effective transportation modes and routes?

SELECT 
    `Supplier name`,
    `Transportation modes`,
    Routes,
    AVG(`Shipping costs`) AS Average_Shipping_Cost
FROM supply_chain_data
GROUP BY `Supplier name`, `Transportation modes`, Routes
ORDER BY `Supplier name`, Average_Shipping_Cost;

-- Which suppliers have the shortest lead times and lowest defect rates?

SELECT 
    `Supplier name`,
    AVG(`Lead time`) AS Average_Lead_Time,
    AVG(`Defect rates`) AS Average_Defect_Rate
FROM supply_chain_data
GROUP BY `Supplier name`
ORDER BY Average_Lead_Time ASC, Average_Defect_Rate ASC;

-- Profitability Analysis:
-- What is the profitability of each product considering both revenue and costs?

SELECT 
    `Product type`,
    SUM(`Price` * `Number of products sold`) AS Total_Revenue,
    SUM(`Manufacturing costs` + `Shipping costs`) AS Total_Costs,
    SUM(`Price` * `Number of products sold`) - SUM(`Manufacturing costs` + `Shipping costs`) AS Profit
FROM supply_chain_data
GROUP BY `Product type`;

-- Can we identify products with low profitability?

SELECT 
    `Product type`,
    SUM(`Price` * `Number of products sold`) AS Total_Revenue,
    SUM(`Manufacturing costs` + `Shipping costs`) AS Total_Costs,
    SUM(`Price` * `Number of products sold`) - SUM(`Manufacturing costs` + `Shipping costs`) AS Profit,
    (SUM(`Price` * `Number of products sold`) - SUM(`Manufacturing costs` + `Shipping costs`)) / SUM(`Price` * `Number of products sold`) * 100 AS Profit_Margin
FROM supply_chain_data
GROUP BY `Product type`
order by Profit_Margin;
