-- Sales Performance Analysis
-- Which product have the highest number of units sold?
SELECT `Product type`, SKU, SUM(`Number of products sold`) AS Total_Units_Sold
FROM supply_chain_data
GROUP BY `Product type` , SKU
ORDER BY `Total_Units_Sold` DESC
LIMIT 1;

-- What is the total revenue generated by each product type?
SELECT `Product type`, round(SUM(Price * `Number of products sold`),2) AS Total_Revenue
FROM supply_chain_data
GROUP BY `Product type`;

-- What is the overall revenue generated from all products?
SELECT ROUND(SUM(Price * `Number of products sold`), 2) AS Overall_Revenue
FROM supply_chain_data;

-- Inventory Management Analysis:
-- What is the current availability of each product?

SELECT `Product type`, SKU, (`Stock levels` - SUM(`Number of products sold`)) AS Current_Availability
FROM supply_chain_data
GROUP BY `Product type`, SKU, `Stock levels`;

-- Which products have low stock levels and may need replenishment?
SELECT `Product type`, SKU, `Stock levels`
FROM supply_chain_data
WHERE `Stock levels` < 10;

-- Supplier Performance Analysis
-- Who are the top-performing suppliers based on the number of products sold?

SELECT `Supplier name`, SUM(`Number of products sold`) AS Total_Products_Sold
FROM supply_chain_data
GROUP BY `Supplier name`
ORDER BY Total_Products_Sold DESC;

-- What are the lead times for each supplier to deliver products?

SELECT `Supplier name`, AVG(`Lead time`) AS Average_Lead_Time
FROM supply_chain_data
GROUP BY `Supplier name`;

-- What is the total revenue generated from products supplied by each supplier?

SELECT `Supplier name`, SUM( Price * `Number of products sold`) AS Total_Revenue
FROM supply_chain_data 
GROUP BY `Supplier name`;


